version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_NAME: im3
      DB_USER: im3_user
      DB_PASSWORD: im3_password
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  updater:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./logs:/var/log
    depends_on:
      - web
      - mariadb
    restart: unless-stopped
    networks:
      - app-network

  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: im3
      MARIADB_USER: im3_user
      MARIADB_PASSWORD: im3_password
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
